### ISSUE TITLE
How to generate all_for_sample.dat file？

### ISSUE THREAD

**Issue by chyeh1126** [Yvonnemamama/GGD#1]
Hi, I try to reproduce the experiment result. I have finished the step of graph generation for each dataset. But when I want to generate the sampled dataset, there is no method to generate a file named "all_for_sample.dat" in the previous step in "preprocessing.py" file and get wrong in this step. Is there any way to generate "all_for_sample.dat" file?

**Comment by YihanMa1** [comment]
Hello, 

This all_for_sample.dat just stores all the graphs you want to sample. It can be any format you want. 
For example, when I am doing this, I used a dict to store all the graphs where the keys are the labels and the items are graphs.
You can just change the sample_dataset function in preprocessing.py accordingly when you use different data formats.

Best,
Yihan
