### ISSUE TITLE
collate_2 in train.py Line 393 and Line 446

### ISSUE THREAD

**Issue by chyeh1126** [Yvonnemamama/GGD#2]
Hello, 
I try to run main.py to get results, but it raises some error in "metric-learning" method. When I check the code, I find that there exists a "collate_2" and it seems not be defined. If I replace the collate_2 with the "collate" that has been defined in Line 42, it raises another error in Line 418 and the error message is "int is not callable". Do you have any solution for this problem?

Best,
ChiaHung

**Comment by YihanMa1** [comment]
Already fixed that. you can check the definition of collate_2 in train.py now.
The collate_2 function is to make sure that the input sample of metric learning is a pair.
